blank_issues_enabled: false
contact_links:
  - name: Planned work
    url: https://github.com/github/primer/issues/new?template=Blank+issue
    about: Tasks that need discussion or just need to be visible for planning.
