// basically for all non high contrast modes
const baseRequirements = [
  // neutral text colors
  [4.5, 'fg.default', 'canvas.default'],
  [4.5, 'fg.muted', 'canvas.default'],
  [4.5, 'fg.subtle', 'canvas.default'],
  [4.5, 'fg.default', 'canvas.subtle'],
  [4.5, 'fg.muted', 'canvas.subtle'],
  [4.5, 'fg.default', 'canvas.inset'],
  [4.5, 'fg.muted', 'canvas.inset'],
  // default text on role bg
  // TODO: contrast does not work with semi-transparent colors
  [4.5, 'fg.default', 'accent.subtle'],
  [4.5, 'fg.default', 'success.subtle'],
  [4.5, 'fg.default', 'open.subtle'],
  [4.5, 'fg.default', 'danger.subtle'],
  [4.5, 'fg.default', 'closed.subtle'],
  [4.5, 'fg.default', 'attention.subtle'],
  [4.5, 'fg.default', 'severe.subtle'],
  [4.5, 'fg.default', 'done.subtle'],
  [4.5, 'fg.default', 'sponsors.subtle'],
  //
  [4.5, 'fg.default', 'accent.muted'],
  [4.5, 'fg.default', 'success.muted'],
  [4.5, 'fg.default', 'open.muted'],
  [4.5, 'fg.default', 'danger.muted'],
  [4.5, 'fg.default', 'closed.muted'],
  [4.5, 'fg.default', 'attention.muted'],
  [4.5, 'fg.default', 'severe.muted'],
  [4.5, 'fg.default', 'done.muted'],
  [4.5, 'fg.default', 'sponsors.muted'],
  // role
  [4.5, 'accent.fg', 'canvas.default'],
  [4.5, 'accent.fg', 'canvas.subtle'],
  [4.5, 'accent.fg', 'canvas.inset'],
  [4.5, 'success.fg', 'canvas.default'],
  [4.5, 'success.fg', 'canvas.subtle'],
  [4.5, 'success.fg', 'canvas.inset'],
  [4.5, 'open.fg', 'canvas.default'],
  [4.5, 'open.fg', 'canvas.subtle'],
  [4.5, 'open.fg', 'canvas.inset'],
  [4.5, 'danger.fg', 'canvas.default'],
  [4.5, 'danger.fg', 'canvas.subtle'],
  [4.5, 'danger.fg', 'canvas.inset'],
  [4.5, 'closed.fg', 'canvas.default'],
  [4.5, 'closed.fg', 'canvas.subtle'],
  [4.5, 'closed.fg', 'canvas.inset'],
  [4.5, 'attention.fg', 'canvas.default'],
  [4.5, 'attention.fg', 'canvas.subtle'],
  [4.5, 'attention.fg', 'canvas.inset'],
  [4.5, 'severe.fg', 'canvas.default'],
  [4.5, 'severe.fg', 'canvas.subtle'],
  [4.5, 'severe.fg', 'canvas.inset'],
  [4.5, 'done.fg', 'canvas.default'],
  [4.5, 'done.fg', 'canvas.subtle'],
  [4.5, 'done.fg', 'canvas.inset'],
  [4.5, 'sponsors.fg', 'canvas.default'],
  [4.5, 'sponsors.fg', 'canvas.subtle'],
  [4.5, 'sponsors.fg', 'canvas.inset'],
  // role text on role bg
  [4.5, 'accent.fg', 'accent.subtle'],
  [4.5, 'success.fg', 'success.subtle'],
  [4.5, 'open.fg', 'open.subtle'],
  [4.5, 'danger.fg', 'danger.subtle'],
  [4.5, 'closed.fg', 'closed.subtle'],
  [4.5, 'addtenion.fg', 'attention.subtle'],
  [4.5, 'severe.fg', 'severe.subtle'],
  [4.5, 'done.fg', 'done.subtle'],
  [4.5, 'sponsors.fg', 'sponsors.subtle'],
  //
  [4.5, 'accent.fg', 'accent.muted'],
  [4.5, 'success.fg', 'success.muted'],
  [4.5, 'open.fg', 'open.muted'],
  [4.5, 'danger.fg', 'danger.muted'],
  [4.5, 'closed.fg', 'closed.muted'],
  [4.5, 'addtenion.fg', 'attention.muted'],
  [4.5, 'severe.fg', 'severe.muted'],
  [4.5, 'done.fg', 'done.muted'],
  [4.5, 'sponsors.fg', 'sponsors.muted'],
  // role text to default text
  [3, 'accent.fg', 'fg.default'],
  [3, 'success.fg', 'fg.default'],
  [3, 'open.fg', 'fg.default'],
  [3, 'danger.fg', 'fg.default'],
  [3, 'closed.fg', 'fg.default'],
  [3, 'attention.fg', 'fg.default'],
  [3, 'severe.fg', 'fg.default'],
  [3, 'done.fg', 'fg.default'],
  [3, 'sponsors.fg', 'fg.default'],
  // fg.onEmphasis
  [4.5, 'fg.onEmphasis', 'neutral.emphasis'],
  [4.5, 'fg.onEmphasis', 'neutral.emphasisPlus'],
  [4.5, 'fg.onEmphasis', 'accent.emphasis'],
  [4.5, 'fg.onEmphasis', 'success.emphasis'],
  [4.5, 'fg.onEmphasis', 'open.emphasis'],
  [4.5, 'fg.onEmphasis', 'danger.emphasis'],
  [4.5, 'fg.onEmphasis', 'closed.emphasis'],
  [4.5, 'fg.onEmphasis', 'attention.emphasis'],
  [4.5, 'fg.onEmphasis', 'severe.emphasis'],
  [4.5, 'fg.onEmphasis', 'done.emphasis'],
  [4.5, 'fg.onEmphasis', 'sponsors.emphasis'],
  // borders
  [3, 'border.default', 'canvas.default'],
  [3, 'border.default', 'canvas.subtle'],
  // TODO: there are no specific border colors for roles
]

export let contrastRequirements: { [key: string]: (number | string)[][] } = {
  // default light mode
  light: baseRequirements,
  light_high_contrast: baseRequirements,
  light_colorblind: baseRequirements,
  light_tritanopia: baseRequirements,
  // default dark mode
  dark: baseRequirements,
  dark_dimmed: baseRequirements,
  dark_high_contrast: baseRequirements,
  dark_colorblind: baseRequirements,
  dark_tritanopia: baseRequirements,
}