export {isBorder} from './isBorder'
export {isColor} from './isColor'
export {isColorWithAlpha} from './isColorWithAlpha'
export {isDeprecated} from './isDeprecated'
export {isShadow} from './isShadow'
export {isSource} from './isSource'
