#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
if npm run lint ; then
    echo "Lint check passed"
else
    echo "[info] Attempt an auto-fix with 'npm run lint:fix'"
    exit 1
fi

if npm run format:check ; then
    echo "Code formatting check passed"
else
    echo "[info] Attempt an auto-fix with 'npm run format'"
    exit 1
fi
