name: Deploy to production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_deploy:
    name: Build and deploy
    uses: primer/.github/.github/workflows/deploy.yml@main
    with:
      node_version: 16
      install: npm ci && cd docs && npm ci && cd ..
      build: cd docs && npm run build
      output_dir: docs/public
