name: Deploy preview

on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write
  deployments: write

jobs:
  deploy:
    name: Build and deploy
    uses: primer/.github/.github/workflows/deploy_preview.yml@main
    with:
      node_version: 14
      install: yarn
      build: yarn build:tokens && yarn build && yarn build:v3 && cd docs && yarn build:preview
      output_dir: docs/public

  post_storybook:
    needs: deploy
    name: Link storybook
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: chrnorm/deployment-action@v2
        name: Post deployment url
        id: deployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment-url: ${{needs.deploy.outputs.deployment_url}}
          environment: storybook-preview
