name: Deploy to production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Build and deploy to production
    uses: primer/.github/.github/workflows/deploy.yml@v2
    with:
      node_version: 20
      install: npm ci --legacy-peer-deps --no-audit --no-fund && npm run install:storybook
      build: npm run build:next && cd docs/storybook && npm run build:prod
      output_dir: docs/public

