name: Deploy to production

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_deploy:
    name: Build and deploy
    uses: primer/.github/.github/workflows/deploy.yml@main
    with:
      node_version: 18
      install: npm ci --legacy-peer-deps --no-audit --no-fund --ignore-scripts && cd docs && npm ci --legacy-peer-deps --no-audit --no-fund --ignore-scripts && cd ..
      build: npm run build:tokens && npm run build && npm run build:next && cd docs && npm run build
      output_dir: docs/public

