# Posts a comment listing all the variables that changed in a PR
name: Diff for design tokens
on:
  pull_request:
    branches-ignore:
      - 'changeset-release/**'
  workflow_dispatch:

jobs:
  changes:
    uses: ./.github/workflows/hasChanged.yml

  diff:
    needs: changes
    if: needs.changes.outputs.outputAffected == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies (pr)
        run: npm ci --no-audit --no-fund --include=dev --ignore-scripts

      - name: Build tokens (pr)
        run: npm run build

      - name: Install dependencies (base)
        run: pushd base; npm i --no-audit --no-fund --ignore-scripts; popd

      - name: Build tokens (base)
        run: pushd base; npm run build; popd

      - name: Install dependecies for diffing
        run: npm install shelljs

      - name: Diff tokens
        id: diff-files
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs')
            const diffFiles = require('./.github/workflows/utilities/diffFiles.cjs')
            await diffFiles('dist/css', '**/**/*.css', 'diff_css.json')
            // read diff file
            const diffs = JSON.parse(fs.readFileSync('diff_css.json', 'utf8'))
            // create sections
            const sections = []
            for (const {title, body} of diffs) {
              sections.push({
                title,
                body
              })
            }
            // set output file paths
            core.setOutput('diffFilePath', [{
              file: 'diff_css.json',
              title: '## Design Token Diff (CSS)',
              sections
            }]);

      - name: Write summary
        uses: actions/github-script@v7
        with:
          script: |
            const addSummary = require('./.github/workflows/utilities/addSummary.cjs')
            const diffFileArray = ${{ steps.diff-files.outputs.diffFilePath }}

            // add summary
            addSummary(diffFileArray, true)

      - name: Comment on pr
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        with:
          script: |
            const addComment = require('./.github/workflows/utilities/addComment.cjs')
            const diffFilePath = ${{ steps.diff-files.outputs.diffFilePath }}
            const WORKFLOW_SUMMARY_URL = `https://github.com/${{env.GITHUB_REPOSITORY}}/actions/runs/${{env.GITHUB_RUN_ID}}`

            for (const diff of diffFilePath) {
              await addComment(diff, WORKFLOW_SUMMARY_URL, context, github)
            }

  remove_comment:
    needs: changes
    if: needs.changes.outputs.outputAffected == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Remove comment and summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const deleteComment = require('./.github/workflows/utilities/deleteCommentByContent.cjs')
            const commentTitles = [
              '## Design Token Diff (CSS)'
            ]
            // delete all comments
            for (const title of commentTitles) {
              await deleteComment(`## ${title}`, context, github)
            }

            // remove summary
            core.summary.clear()
            core.summary.write({overwrite: true})
