name: Prepare VRT assets

on:
  workflow_call:
    inputs:
      node_version:
        description: Node.js version to use
        required: false
        type: string
        default: '22'

jobs:
  build:
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npm run storybook:install

      - name: Build tokens
        run: npm run build

      - name: Build storybook
        working-directory: docs/storybook
        run: npm run build-storybook

      - name: Upload VRT assets
        uses: actions/upload-artifact@v4
        with:
          name: vrt-assets
          path: |
            dist
            docs/storybook/storybook-static
          retention-days: 1
