name: Release Canary
on:
  push:
    branches-ignore:
      - 'main'
      - 'changeset-release/**'
      - 'dependabot/**'

jobs:
  release-canary:
    name: Canary
    if: ${{ github.repository == 'primer/primitives' }}
    uses: primer/.github/.github/workflows/release_canary.yml@main
    with:
      install: npm ci --legacy-peer-deps --no-audit --no-fund --include=dev && npm run build && npm run build:tokens
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
